import Head from 'next/head';
import axios from "axios";
import  styles from "../styles/Home.module.css"
import { useRouter } from 'next/router';
export default function Home(props) {
  const{movies}=props;
  const router=useRouter();
 
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app , Movie App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1 className={styles.heading}>Movie-App</h1>

        <div className={styles.movies}>
          {
            movies?.map((movie)=>{
              return <div key={movie.id}>
                 <img src={movie.Poster} alt={movie.Title}/>
                 <p>Movie :- {movie.Title}</p>
                 <p>Year :- {movie.Year}</p>
                 <button onClick={()=>router.push(`/${movie.id}`)}>
                  See More
                 </button>
              </div>
            })
          }
            
        </div>
         
            
      </main>

      
         
    </div>
  )
}


export async function getServerSideProps(){
  let res=await axios.get("http://localhost:8080/movies");
  let data= res.data;
  
  return{
    props:{
      movies:data
    }
  }

}